### ISSUE TITLE
Need guidance to upgrade c3 to rc0

### ISSUE THREAD

**Issue by technoob91** [mhartington/ionicv2-c3js#4]
Hi @mhartington ,
          I've used your example as template to implement c3 charts in my project. Now after upgrading to Ionic rc0 (which is great by the way) I've followed the steps in the changelog and used @types. First i got errors saying c3 is not a module so i added the following lines to index.t.s

export = c3;
export as namespace c3;

Which solved that error but after the page loads i get these errors.

Uncaught TypeError: Cannot read property 'document' of undefined       d3.js:8

If you could upgrade your example to the latest version or guide me as to how to fix this error you would be helping a lost soul :)

Thanks in advance
Aashish R

**Comment by technoob91** [comment]
hi,
    So I have just added the library directly in index.html and used **declare var c3;** for now and it works. It'll be great though if you could help me do it the right way. 

Thanks

**Comment by tuna1207** [comment]
hi technoob91 , could you tell me how do you add library directly to index.html and where do you declare var c3 , i'm having problem with rc0 too :(. 
I added :
`<script src="node_modules/c3/c3.js"></script>` to index.html and
`declare var c3` in my .ts file but still getting the error c3 is not defined.

Thanks :D

**Comment by technoob91** [comment]
Hey @tunguyenbhtech ,
     I used the cdn link directly instead of using node_modules directly. I faced the same problem as you but giving the cdn link solved the issue. Let me know if it worked.

Aashish

**Comment by tuna1207** [comment]
I see , thanks Aashish , the cdn worked :D. We still need to figure out a way to import c3 from node_modules. I'm trying to make it work like this [https://forum.ionicframework.com/t/rc0-how-to-export-components-and-other-features-properly/65389/11](url) but haven't succeeded .

**Comment by technoob91** [comment]
@tunguyenbhtech  your url leads to a 404 page. The node modules was working till beta 11 now we need to use @types instead was not able to get it working that way. Will do some more research when I get some time but do let me know if you figure it out.

**Comment by tuna1207** [comment]
@technoob91 ah sorry maybe this url will work https://forum.ionicframework.com/t/rc0-how-to-export-components-and-other-features-properly/65389/11.
Yes i'm trying to get @types to work too , will let you know if i could figure it out :D.

**Comment by gurisko** [comment]
@tunguyenbhtech Is there a way you can do a pull request for this repo?

**Comment by tuna1207** [comment]
Hi guys @technoob91 ,@gurisko the problem is solved here 
https://forum.ionicframework.com/t/rc0-how-to-import-c3-c3js-chart/65727/6
with @types :D.
